# Generated by Django 5.1.5 on 2025-01-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_alter_query_id_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='query',
        ),
        migrations.AddField(
            model_name='query',
            name='country_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='state_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
