# Generated by Django 5.1.5 on 2025-01-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_remove_query_query_query_country_code_query_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
