# Generated by Django 5.1.5 on 2025-01-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_query_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='id',
            new_name='query_id',
        ),
    ]
